[package]
name = "advent-of-code-2023-rust"
version = "0.1.0"
edition = "2021"
authors = [ "Jeroen Donkers <jeroenwzelf@gmail.com>" ]

[dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "benchmark_all"
harness = false
